Add PHP 8.0 support
laminas/laminas-mime pull request #14
Opened 2020-11-23 19:55 UTC by bfoosness

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Close #13

2020-12-10 23:16 UTC, snapshotpl requested changes

2020-12-10 23:16 UTC, snapshotpl commented on .travis.yml
> +    - php: 'nightly'
`8.0` is supported now

2021-01-14 09:38 UTC, glensc commented on .travis.yml
> -    - php: 5.6
"Update .travis.yml" is not much useful commit message. seems like clickbait.

2021-01-28 10:20 UTC, Slamdunk approved these changes

2021-02-09 13:15 UTC, netiul commented
What is the status of this?

2021-02-09 13:23 UTC, bfoosness commented
> What is the status of this?

As far as I know it's done, and it was previously approved. I'm just waiting on either feedback or a merge.

2021-02-16 17:40 UTC, merged